dp: Fix broken no_std builds
In commits 62c224e84d08 ("dp: peripheral: Store process images in
`managed` slices") and 838ed88791ee ("dp: diagnostics: Store diagnostics
in a `managed` slice"), `ManagedSlice`s were introduced for storing the
buffers of a peripheral.  Unfortunately, a small oversight where an
std-only conversion was used lead to these commits breaking `no_std`
usage of profirust.

Compiler errors like this one could be observed by downstream users
trying to build profirust without the `std` feature:

	error[E0277]: the trait bound `ManagedSlice<'_, u8>: From<[_; 0]>` is not satisfied

Fortunately, this is easily fixed by using a different approach for
creating empty `ManagedSlice`s.

Fixes: 62c224e84d08 ("dp: peripheral: Store process images in `managed` slices")
Fixes: 838ed88791ee ("dp: diagnostics: Store diagnostics in a `managed` slice")